---
abstract: 'Net::Pcap wrapper with AnyEvent'
author:
  - 'Takeshi Miki <miki@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Pcap
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent: 0
  Class::Accessor::Fast: 0
  Net::Pcap: 0
  NetPacket::Ethernet: 0
  NetPacket::IP: 0
  NetPacket::TCP: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.00001
